-- 全量建表脚本（MySQL，手工参考）
-- 应用启动时由 DatabaseMigrationService 自动检测并创建

CREATE TABLE T_SYS_SEQ (
   NAME VARCHAR(50) NOT NULL,
   NEXT_VAL BIGINT NOT NULL,
   PRIMARY KEY (NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO T_SYS_SEQ (NAME, NEXT_VAL) VALUES ('TICKET_NO', 1);

CREATE TABLE T_USER (
   ID VARCHAR(36) NOT NULL,
   USERNAME VARCHAR(50) NOT NULL,
   PASSWORD VARCHAR(100) NOT NULL,
   DISPLAY_NAME VARCHAR(50) NOT NULL,
   ENABLED TINYINT(1) NOT NULL DEFAULT 0,
   CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (ID),
   UNIQUE KEY UK_T_USER_USERNAME (USERNAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE T_ARCHIVE (
   ID VARCHAR(36) NOT NULL,
   PROJECT_NAME VARCHAR(200) NOT NULL,
   PROJECT_TYPE VARCHAR(100),
   LAUNCH_DATE DATE,
   MAINT_EXPIRE_DATE DATE,
   LAUNCH_PLAN TEXT,
   SPECIAL_PROCESS TEXT,
   CONTACT_INFO TEXT,
   REMOTE_METHOD TEXT,
   ONSITE_MANAGER VARCHAR(100),
   IMPL_MANAGER VARCHAR(100),
   CREATE_BY VARCHAR(50),
   CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE T_TICKET (
   ID VARCHAR(36) NOT NULL,
   ARCHIVE_ID VARCHAR(36) NOT NULL,
   ORDER_TYPE VARCHAR(30) NOT NULL,
   CONTENT TEXT,
   CONTACT_INFO TEXT,
   SUBMITTER VARCHAR(50),
   HANDLER VARCHAR(50),
   STATUS VARCHAR(20) DEFAULT '已提交',
   EXPECTED_COMPLETE_DATE DATE,
   TARGET_COMPLETE_DATE DATE,
   ATTENTION_NOTE TEXT,
   PROCESS_NOTE TEXT,
   UPGRADE_BY VARCHAR(50),
   UPGRADE_TIME DATETIME,
   TICKET_NO BIGINT,
   CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (ID),
   UNIQUE KEY UK_T_TICKET_NO (TICKET_NO),
   KEY IDX_T_TICKET_ARCHIVE (ARCHIVE_ID),
   CONSTRAINT FK_T_TICKET_ARCHIVE FOREIGN KEY (ARCHIVE_ID) REFERENCES T_ARCHIVE (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE T_TICKET_FOLLOWUP (
   ID VARCHAR(36) NOT NULL,
   TICKET_ID VARCHAR(36) NOT NULL,
   CONTENT TEXT NOT NULL,
   CREATE_BY VARCHAR(50),
   CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (ID),
   KEY IDX_T_FOLLOWUP_TICKET (TICKET_ID),
   CONSTRAINT FK_T_FOLLOWUP_TICKET FOREIGN KEY (TICKET_ID) REFERENCES T_TICKET (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE T_TICKET_PROCESS (
   ID VARCHAR(36) NOT NULL,
   TICKET_ID VARCHAR(36) NOT NULL,
   PARENT_ID VARCHAR(36) DEFAULT NULL,
   ACTION_TYPE VARCHAR(20) NOT NULL,
   HANDLE_METHOD VARCHAR(100) DEFAULT NULL,
   CONTENT TEXT,
   CREATE_BY VARCHAR(50),
   CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (ID),
   KEY IDX_T_PROCESS_TICKET (TICKET_ID),
   KEY IDX_T_PROCESS_PARENT (PARENT_ID),
   CONSTRAINT FK_T_PROCESS_TICKET FOREIGN KEY (TICKET_ID) REFERENCES T_TICKET (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE T_TICKET_ATTACHMENT (
   ID VARCHAR(36) NOT NULL,
   TICKET_ID VARCHAR(36) NOT NULL,
   ATTACHMENT_TYPE VARCHAR(20) NOT NULL,
   ORIGINAL_NAME VARCHAR(255) NOT NULL,
   STORED_NAME VARCHAR(255) NOT NULL,
   RELATIVE_PATH VARCHAR(500) NOT NULL,
   CONTENT_TYPE VARCHAR(100),
   FILE_SIZE BIGINT,
   CREATE_BY VARCHAR(50),
   CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (ID),
   KEY IDX_T_ATTACH_TICKET (TICKET_ID),
   CONSTRAINT FK_T_ATTACH_TICKET FOREIGN KEY (TICKET_ID) REFERENCES T_TICKET (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE T_ARCHIVE_ATTACHMENT (
   ID VARCHAR(36) NOT NULL,
   ARCHIVE_ID VARCHAR(36) NOT NULL,
   ORIGINAL_NAME VARCHAR(255) NOT NULL,
   STORED_NAME VARCHAR(255) NOT NULL,
   RELATIVE_PATH VARCHAR(500) NOT NULL,
   CONTENT_TYPE VARCHAR(100),
   FILE_SIZE BIGINT,
   CREATE_BY VARCHAR(50),
   CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (ID),
   KEY IDX_T_ATTACH_ARCHIVE (ARCHIVE_ID),
   CONSTRAINT FK_T_ATTACH_ARCHIVE FOREIGN KEY (ARCHIVE_ID) REFERENCES T_ARCHIVE (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE T_REMINDER (
   ID VARCHAR(36) NOT NULL,
   TICKET_ID VARCHAR(36) NOT NULL,
   TARGET_USER VARCHAR(50) NOT NULL,
   MESSAGE VARCHAR(500) NOT NULL,
   REMIND_DATE DATE NOT NULL,
   REMIND_HOUR TINYINT NOT NULL,
   IS_READ VARCHAR(1) NOT NULL DEFAULT '0',
   CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (ID),
   CONSTRAINT FK_T_REMINDER_TICKET FOREIGN KEY (TICKET_ID) REFERENCES T_TICKET (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
