-- 以下增量变更已由应用启动时自动执行（DatabaseMigrationService）

-- 系统序号表（替代 Oracle SEQUENCE）
CREATE TABLE T_SYS_SEQ (
   NAME VARCHAR(50) NOT NULL,
   NEXT_VAL BIGINT NOT NULL,
   PRIMARY KEY (NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO T_SYS_SEQ (NAME, NEXT_VAL) VALUES ('TICKET_NO', 1);

-- 工单：自增序号
ALTER TABLE T_TICKET ADD COLUMN TICKET_NO BIGINT;
CREATE UNIQUE INDEX UK_T_TICKET_NO ON T_TICKET (TICKET_NO);

-- 工单：升级人、升级时间
ALTER TABLE T_TICKET ADD COLUMN UPGRADE_BY VARCHAR(50);
ALTER TABLE T_TICKET ADD COLUMN UPGRADE_TIME DATETIME;

-- 用户表：启用状态（注册默认停用，需管理员审核）
ALTER TABLE T_USER ADD COLUMN ENABLED TINYINT(1) NOT NULL DEFAULT 0;
UPDATE T_USER SET ENABLED = 1;

-- 档案附件表
CREATE TABLE T_ARCHIVE_ATTACHMENT (
   ID VARCHAR(36) NOT NULL,
   ARCHIVE_ID VARCHAR(36) NOT NULL,
   ORIGINAL_NAME VARCHAR(255) NOT NULL,
   STORED_NAME VARCHAR(255) NOT NULL,
   RELATIVE_PATH VARCHAR(500) NOT NULL,
   CONTENT_TYPE VARCHAR(100),
   FILE_SIZE BIGINT,
   CREATE_BY VARCHAR(50),
   CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (ID),
   KEY IDX_T_ATTACH_ARCHIVE (ARCHIVE_ID),
   CONSTRAINT FK_T_ATTACH_ARCHIVE FOREIGN KEY (ARCHIVE_ID) REFERENCES T_ARCHIVE (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 工单附件表
CREATE TABLE T_TICKET_ATTACHMENT (
   ID VARCHAR(36) NOT NULL,
   TICKET_ID VARCHAR(36) NOT NULL,
   ATTACHMENT_TYPE VARCHAR(10) NOT NULL,
   ORIGINAL_NAME VARCHAR(255) NOT NULL,
   STORED_NAME VARCHAR(255) NOT NULL,
   RELATIVE_PATH VARCHAR(500) NOT NULL,
   CONTENT_TYPE VARCHAR(100),
   FILE_SIZE BIGINT,
   CREATE_BY VARCHAR(50),
   CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (ID),
   KEY IDX_T_ATTACH_TICKET (TICKET_ID),
   CONSTRAINT FK_T_ATTACH_TICKET FOREIGN KEY (TICKET_ID) REFERENCES T_TICKET (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 工单：目标完成时间、注意事项
ALTER TABLE T_TICKET ADD COLUMN TARGET_COMPLETE_DATE DATE;
ALTER TABLE T_TICKET ADD COLUMN ATTENTION_NOTE TEXT;

-- 将旧 PROCESS_NOTE 迁移到跟进记录表（一次性）
INSERT INTO T_TICKET_FOLLOWUP (ID, TICKET_ID, CONTENT, CREATE_BY, CREATE_TIME)
SELECT UUID(), ID, PROCESS_NOTE, HANDLER, CREATE_TIME
FROM T_TICKET
WHERE PROCESS_NOTE IS NOT NULL AND LENGTH(PROCESS_NOTE) > 0
  AND NOT EXISTS (SELECT 1 FROM T_TICKET_FOLLOWUP f WHERE f.TICKET_ID = T_TICKET.ID);
